version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_import_data.R
    needs: [generate_dataset]
    outputs: 
      highly_sensitive:
        cleandata: output/data_edited.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt
      
  create_table1: 
    run: > 
      r:latest
        analysis/020_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/shielding_table1.html
        table1_r: output/tables/shielding_table1_redacted.html
        table1_data: output/table1_data.csv
        table2_shielding_v0: output/tables/shielding_table2.html
        table2_shielding_v1: output/tables/shielding_v1_table2.html
        table2_shielding_v2: output/tables/shielding_v2_table2.html
  

  SEIUHRD_fit:
    run: > 
      r:latest
        modelling/SEIRmodel_main.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        txt10: output/modelling/J4h_Simul_run.txt
        csv10: output/modelling/J4h_Simul_R0_by_week.csv
        txt11: output/modelling/J4h_Contact_matrix_year-start-24Feb20_stats.txt
        pdf10: output/modelling/J4h_Data_Incidence.pdf
        pdf11: output/modelling/J4h_Fit_MCMC_BT.pdf
        pdf12: output/modelling/J4h_Fit_Variables_estimated.pdf
        pdf13: output/modelling/J4h_Fit_Variables_data1.pdf
        pdf14: output/modelling/J4h_Fit_Variables_data2.pdf
        txt12: output/modelling/J4h_Fit_Bayesian_report.txt
        pdf15: output/figures/J4h_covid_hosp_over_time2again.pdf
        pdf16: output/figures/J4h_covid_deaths_over_time2again.pdf

 