version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_import_data.R
    needs: [generate_dataset]
    outputs: 
      highly_sensitive:
        cleandata: output/data_edited.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt
      
  create_table1: 
    run: > 
      r:latest
        analysis/020_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/shielding_table1.html
        table1_r: output/tables/shielding_table1_redacted.html
        table1_data: output/table1_data.csv
        table2_shielding_v0: output/tables/shielding_table2.html
        table2_shielding_v1: output/tables/shielding_v1_table2.html
        table2_shielding_v2: output/tables/shielding_v2_table2.html
  
  HD_data:
    run: > 
      r:latest
        analysis/SEIUHRD_HDdata.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        pdf01: output/HDsynthesis/HDdata_subsets.pdf
        csv01: output/HDsynthesis/datDh.csv
        csv02: output/HDsynthesis/datDhd.csv
        csv03: output/HDsynthesis/datDd.csv
        pdf02: output/HDsynthesis/HDdata_Incidence.pdf
        txt01: output/HDsynthesis/HDdata_summary.txt
        csv04: output/HDsynthesis/HDdata_a1to9.csv
        csv041: output/HDsynthesis/HDdata_a1.csv
        csv042: output/HDsynthesis/HDdata_a2.csv
        csv043: output/HDsynthesis/HDdata_a3.csv
        csv044: output/HDsynthesis/HDdata_a4.csv
        csv045: output/HDsynthesis/HDdata_a5.csv
        csv046: output/HDsynthesis/HDdata_a6.csv
        csv047: output/HDsynthesis/HDdata_a7.csv
        csv048: output/HDsynthesis/HDdata_a8.csv
        csv049: output/HDsynthesis/HDdata_a9.csv


 