version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_import_data.R
    needs: [generate_dataset]
    outputs: 
      highly_sensitive:
        cleandata: output/data_edited.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt
      
  create_table1: 
    run: > 
      r:latest
        analysis/020_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/shielding_table1.html
        table1_r: output/tables/shielding_table1_redacted.html
        table1_data: output/table1_data.csv
        table2_shielding_v0: output/tables/shielding_table2.html
        table2_shielding_v1: output/tables/shielding_v1_table2.html
        table2_shielding_v2: output/tables/shielding_v2_table2.html
  
  HD_data_questions:
    run: > 
      r:latest
        analysis/SEIUHRD_HDdata_questions.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        pdf01: output/HDsynthesis/JDat5_HDdata_questions_answered_Hospital_wCH.pdf
        txt01: output/HDsynthesis/JDat5_HDdata_questions_answered_Hospital_wCH.txt
        pdf02: output/HDsynthesis/JDat5_HDdata_questions_answered_Deaths_wCH.pdf
        txt02: output/HDsynthesis/JDat5_HDdata_questions_answered_Deaths_wCH.txt
        pdf03: output/HDsynthesis/JDat5_HDdata_questions_answered_Shielding_wCH.pdf
        txt03: output/HDsynthesis/JDat5_HDdata_questions_answered_Shielding_wCH.txt
        pdf04: output/HDsynthesis/JDat5_HDdata_questions_answered_Hospital.pdf
        txt04: output/HDsynthesis/JDat5_HDdata_questions_answered_Hospital.txt
        pdf05: output/HDsynthesis/JDat5_HDdata_questions_answered_Deaths.pdf
        txt05: output/HDsynthesis/JDat5_HDdata_questions_answered_Deaths.txt
        pdf06: output/HDsynthesis/JDat5_HDdata_questions_answered_Shielding.pdf
        txt06: output/HDsynthesis/JDat5_HDdata_questions_answered_Shielding.txt

  HD_data:
    run: > 
      r:latest
        analysis/SEIUHRD_HDdata.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        pdf01b: output/HDsynthesis/JDat5_HDdata_H,D_Carehomes.pdf
        pdf02b: output/HDsynthesis/JDat5_HDdata_H,HR,DH,DO.pdf
        pdf03b: output/HDsynthesis/JDat5_HDdata_Incidence.pdf
        txt01b: output/HDsynthesis/JDat5_HDdata_summary.txt
        csv01b: output/HDsynthesis/JDat5_HDdata_H_Carehomes.csv
        csv02b: output/HDsynthesis/JDat5_HDdata_D_Carehomes.csv
        csv03b: output/HDsynthesis/JDat5_HDdata_DH_Carehomes.csv
        csv04b: output/HDsynthesis/JDat5_HDdata_DO_Carehomes.csv
        csv05b: output/HDsynthesis/JDat5_Hdata.csv
        csv06b: output/HDsynthesis/JDat5_HRdata.csv
        csv07b: output/HDsynthesis/JDat5_DHdata.csv
        csv08b: output/HDsynthesis/JDat5_DOdata.csv
