version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_import_data.R
    needs: [generate_dataset]
    outputs: 
      highly_sensitive:
        cleandata: output/data_edited.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt
      
  create_table1: 
    run: > 
      r:latest
        analysis/020_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/shielding_table1.html
        table1_r: output/tables/shielding_table1_redacted.html
        table1_data: output/table1_data.csv
        table2_shielding_v0: output/tables/shielding_table2.html
        table2_shielding_v1: output/tables/shielding_v1_table2.html
        table2_shielding_v2: output/tables/shielding_v2_table2.html
  
  HD_data_questions:
    run: > 
      r:latest
        analysis/SEIUHRD_HDdata_questions.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        txt01: output/HDsynthesis/JDat10_HDdata_questions_answered_Hospital_wCH.txt
        txt02: output/HDsynthesis/JDat10_HDdata_questions_answered_Deaths_wCH.txt
        txt03: output/HDsynthesis/JDat10_HDdata_questions_answered_Shielding_wCH.txt
        txt04: output/HDsynthesis/JDat10_HDdata_questions_answered_Hospital.txt
        txt05: output/HDsynthesis/JDat10_HDdata_questions_answered_Deaths.txt
        txt06: output/HDsynthesis/JDat10_HDdata_questions_answered_Shielding.txt

  HD_data:
    run: > 
      r:latest
        analysis/runmkd.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        csv01b: output/HDsynthesis/JDat10_Carehomes_included_H.csv
        svg01b: output/HDsynthesis/JDat10_Carehomes_included_H.svg
        csv02b: output/HDsynthesis/JDat10_Carehomes_included_D.csv
        svg02b: output/HDsynthesis/JDat10_Carehomes_included_D.svg
        csv03b: output/HDsynthesis/JDat10_Carehomes_included_DH.csv
        svg03b: output/HDsynthesis/JDat10_Carehomes_included_DH.svg
        csv04b: output/HDsynthesis/JDat10_Carehomes_included_DO.csv
        svg04b: output/HDsynthesis/JDat10_Carehomes_included_DO.svg
        csv051: output/HDsynthesis/JDat10_Hdata_all.csv
        svg051: output/HDsynthesis/JDat10_Hdata_all.svg
        csv052: output/HDsynthesis/JDat10_Hdata_by_age.csv
        svg052: output/HDsynthesis/JDat10_Hdata_by_age.svg
        csv053: output/HDsynthesis/JDat10_Hdata_by_shi.csv
        svg053: output/HDsynthesis/JDat10_Hdata_by_shi.svg
        csv054: output/HDsynthesis/JDat10_Hdata_s_by_age.csv
        svg054: output/HDsynthesis/JDat10_Hdata_s0_by_age.svg
        svg055: output/HDsynthesis/JDat10_Hdata_s1_by_age.svg
        csv061: output/HDsynthesis/JDat10_HRdata_all.csv
        svg061: output/HDsynthesis/JDat10_HRdata_all.svg
        csv062: output/HDsynthesis/JDat10_HRdata_by_age.csv
        svg062: output/HDsynthesis/JDat10_HRdata_by_age.svg
        csv063: output/HDsynthesis/JDat10_HRdata_by_shi.csv
        svg063: output/HDsynthesis/JDat10_HRdata_by_shi.svg
        csv064: output/HDsynthesis/JDat10_HRdata_s_by_age.csv
        svg064: output/HDsynthesis/JDat10_HRdata_s0_by_age.svg
        svg065: output/HDsynthesis/JDat10_HRdata_s1_by_age.svg
        csv071: output/HDsynthesis/JDat10_DHdata_all.csv
        svg071: output/HDsynthesis/JDat10_DHdata_all.svg
        csv072: output/HDsynthesis/JDat10_DHdata_by_age.csv
        svg072: output/HDsynthesis/JDat10_DHdata_by_age.svg
        csv073: output/HDsynthesis/JDat10_DHdata_by_shi.csv
        svg073: output/HDsynthesis/JDat10_DHdata_by_shi.svg
        csv074: output/HDsynthesis/JDat10_DHdata_s_by_age.csv
        svg074: output/HDsynthesis/JDat10_DHdata_s0_by_age.svg
        svg075: output/HDsynthesis/JDat10_DHdata_s1_by_age.svg
        csv081: output/HDsynthesis/JDat10_DOdata_all.csv
        svg081: output/HDsynthesis/JDat10_DOdata_all.svg
        csv082: output/HDsynthesis/JDat10_DOdata_by_age.csv
        svg082: output/HDsynthesis/JDat10_DOdata_by_age.svg
        csv083: output/HDsynthesis/JDat10_DOdata_by_shi.csv
        svg083: output/HDsynthesis/JDat10_DOdata_by_shi.svg
        csv084: output/HDsynthesis/JDat10_DOdata_s_by_age.csv
        svg084: output/HDsynthesis/JDat10_DOdata_s0_by_age.svg
        svg085: output/HDsynthesis/JDat10_DOdata_s1_by_age.svg       
        csv091: output/HDsynthesis/JDat10_H,HR,DH,DOdata_H.csv
        csv092: output/HDsynthesis/JDat10_H,HR,DH,DOdata_HR.csv
        csv093: output/HDsynthesis/JDat10_H,HR,DH,DOdata_DH.csv
        csv094: output/HDsynthesis/JDat10_H,HR,DH,DOdata_DO.csv
        svg09b: output/HDsynthesis/JDat10_H,HR,DH,DOdata.svg
        html01: output/HDsynthesis/JDat10_Report_HDdata.html
