version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/databuilder_definition.py --output output/dataset_all.csv.gz
    outputs:
      highly_sensitive:
        dataset_all: output/dataset_all.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_import_data.R
    needs: [generate_dataset]
    outputs: 
      highly_sensitive:
        cleandata: output/data_edited.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt
      
  create_table1: 
    run: > 
      r:latest
        analysis/020_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/shielding_table1.html
        table1_r: output/tables/shielding_table1_redacted.html
        table1_data: output/table1_data.csv
        table2_shielding_v0: output/tables/shielding_table2.html
        table2_shielding_v1: output/tables/shielding_v1_table2.html
        table2_shielding_v2: output/tables/shielding_v2_table2.html
  
  HD_data_questions:
    run: > 
      r:latest
        analysis/SEIUHRD_HDdata_questions.r
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        txt01: output/HDsynthesis/JDat6_HDdata_questions_answered_Hospital_wCH.txt
        txt02: output/HDsynthesis/JDat6_HDdata_questions_answered_Deaths_wCH.txt
        txt03: output/HDsynthesis/JDat6_HDdata_questions_answered_Shielding_wCH.txt
        txt04: output/HDsynthesis/JDat6_HDdata_questions_answered_Hospital.txt
        txt05: output/HDsynthesis/JDat6_HDdata_questions_answered_Deaths.txt
        txt06: output/HDsynthesis/JDat6_HDdata_questions_answered_Shielding.txt

  # HD_data:
    # run: > 
      # r:latest
        # analysis/runmkd.r
    # needs: [clean_the_data]
    # outputs:
      # moderately_sensitive:
        # csv01b: output/HDsynthesis/JDat6_Carehomes_included_H.csv
        # csv02b: output/HDsynthesis/JDat6_Carehomes_included_D.csv
        # csv03b: output/HDsynthesis/JDat6_Carehomes_included_DH.csv
        # csv04b: output/HDsynthesis/JDat6_Carehomes_included_DO.csv
        # csv05b: output/HDsynthesis/JDat6_Hdata.csv
        # csv06b: output/HDsynthesis/JDat6_HRdata.csv
        # csv07b: output/HDsynthesis/JDat6_DHdata.csv
        # csv08b: output/HDsynthesis/JDat6_DOdata.csv
        # html01: output/HDsynthesis/HDdata.html
